- name: Create target install dir
  file:
    path: "{{ BWAMEM_ROOT }}"
    state: 'directory'
    owner: "{{ BWAMEM_USER }}"
    group: "{{ BWAMEM_GROUP }}"
    mode: "0755"

- name: Download and install DockStore script
  get_url: url={{ item.src }} dest="{{ item.dest }}" mode=0777 validate_certs=no
  with_items:
    - "{{ dockstore_package }}"
  register: result
  until: result|success
  retries: 1

- name: Setup required CWL dependencies
  pip: name="{{ item.name }}" version="{{ item.version }}"
  with_items:
    - "{{ cwl_packages }}"

- name: Copy sample files
  copy: src="samples" dest="{{ BWAMEM_ROOT }}/" owner={{ BWAMEM_USER }} group={{ BWAMEM_GROUP }}
  
- name: Copy the workflow job script
  template: src=run_workflow.j2 dest="{{ BWAMEM_ROOT }}/run_workflow.sh" mode=0700 owner="{{ BWAMEM_USER }}" group="{{ BWAMEM_GROUP }}"
    
- name: Copy the version info file into GVLDash
  template: src=version_info.j2 dest="{{ gvl_install_path }}/info/pancancer_bwamem_workflow.yml"
